name: pypi deploy

on:
  release:
    types: [created]


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Instala nix single user
      run: |
        wget -qO- http://ix.io/4Cj0 | sh \
        && . "$HOME"/."$(basename $SHELL)"rc \
        && nix flake --version \
        && direnv --version
        echo "$HOME"/.nix-profile/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        nix develop .# --command sh -c 'make poetry.config.venv && make poetry.install'

    - name: build package
      run: |
        nix develop .# --command sh -c 'make package.build'

    - name: deploy package
      env:
        PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: make package.publish PASSWORD=$PASSWORD

