name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black flake8

      - name: Lint code with black
        run: black --check .

      - name: Lint code with flake8
        run: flake8

  test:
    name: test [${{ matrix.os }}] (${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: make pip.install

      - name: Config env
        run: make config.env

      - name: Test with pytest
        run: make test

  coverage:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make pip.install

      - name: Config env
        run: make config.env

      - name: make coverage
        run: make coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
          
