name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.8

      - name: Install dependencies
        run: |
          ls -al
          make poetry.config.venv
          make poetry.install
          ls -al
          ls -al ~/.cache/pypoetry

      - name: Lint code with black
        run: make fmt.check

  test:
    name: test [${{ matrix.os }}] (${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.8

      - name: Install dependencies
        run: |
          make poetry.config.native
          make poetry.install

      - name: Config env
        run: make config.env

      - name: Test with pytest
        run: make test

  coverage:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.8

      - name: Install dependencies
        run: |
          make poetry.config.native
          make poetry.install

      - name: Config env
        run: make config.env

      - name: make coverage
        run: make coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
          
