name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: false
          virtualenvs-in-project: false
          virtualenvs-path: .

      - name: Lint code with black
        run: |
          make fmt.check

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: false
          virtualenvs-in-project: false
          virtualenvs-path: .

      - name: Config env
        run: make config.env

      - name: Test with pytest
        run: make test
